FROM php:8.0.1-fpm-alpine3.12   

COPY php/php.ini /usr/local/etc/php/php.ini
 
RUN curl 'http://pecl.php.net/get/mongodb-1.5.1.tgz' -o mongodb-1.5.1.tgz \

    && pecl install mongodb-1.5.1.tgz \

    && docker-php-ext-enable mongodb \

    && rm mongodb-1.5.1.tgz \

    && rm -rf mongodb-1.5.1 \

   && echo "成功添加mongodb!" \

   && curl 'http://pecl.php.net/get/redis-4.1.0.tgz' -o redis-4.1.0.tgz \

   && pecl install redis-4.1.0.tgz \

   && docker-php-ext-enable redis \

   && rm redis-4.1.0.tgz \

   && rm -rf redis-4.1.0 \

   && echo "成功添加redis扩展!"

EXPOSE 9000
CMD ["php-fpm"]
##</autogenerated>##
